/* jmd import — stage 1, mechanical: a .pptx → a draft .jmd, its media, a brand draft and a report.
   Deterministic, zero dependencies: the .pptx is a zip of XML (tools/zip.mjs), text and pictures are read
   with targeted patterns, images are resized by headless Chrome (canvas) so the same code runs everywhere.
   Stage 2 — restructuring the draft into blocks (cards, compare…) — is the agent's job, with the report and
   the original slide images in hand. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { readZip } from '../tools/zip.mjs';
import { Browser } from '../tools/cdp.mjs';

const EMU = 12700; // EMU per point; slides are 960×540 pt (16:9) in Office
const unesc = s => s.replace(/&#x([0-9A-Fa-f]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16))).replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(+d)).replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&');
// Office's automatic alt texts are noise, not captions
const cleanAlt = a => /générée automatiquement|automatically generated|généré par l.IA|generated by AI|AI-generated|^Une image contenant|^A picture containing|^An image containing|^Image \d+$|^Picture \d+$|^Graphique \d+$/i.test(a) ? '' : a.replace(/\s+/g, ' ').trim();

/* ── XML helpers (targeted, not a parser) ─────────────────────────────── */
function rels(z, path) {
  const dir = path.replace(/[^/]+$/, ''), file = dir + '_rels/' + basename(path) + '.rels';
  const x = z.text(file) || '';
  const out = {};
  for (const m of x.matchAll(/<Relationship\s+[^>]*?Id="([^"]+)"[^>]*?Target="([^"]+)"[^>]*?\/?>/g)) {
    const t = m[2].startsWith('/') ? m[2].slice(1) : join(dir, m[2]).replace(/\\/g, '/');
    out[m[1]] = t.replace(/^ppt\/slides\/\.\.\//, 'ppt/');
  }
  return out;
}
// paragraphs of a shape: [{ text, bullet, level, size, bold }]
function paragraphs(sp) {
  const out = [];
  for (const p of sp.match(/<a:p>[\s\S]*?<\/a:p>|<a:p\/>/g) || []) {
    const runs = [...p.matchAll(/<a:r>([\s\S]*?)<\/a:r>/g)].map(m => {
      const r = m[1];
      const t = (r.match(/<a:t>([^<]*)<\/a:t>/) || [])[1] || '';
      const bold = /<a:rPr[^>]*\sb="1"/.test(r);
      const size = +((/<a:rPr[^>]*\ssz="(\d+)"/.exec(r) || [])[1] || 0) / 100;
      return { t: unesc(t), bold, size };
    }).filter(r => r.t);
    if (!runs.length) continue;
    const allBold = runs.every(r => r.bold);
    const text = runs.map(r => {
      if (!r.bold || allBold || !r.t.trim()) return r.t;
      const lead = /^\s*/.exec(r.t)[0], trail = /\s*$/.exec(r.t)[0];
      return lead + '**' + r.t.trim() + '**' + trail;
    }).join('').replace(/\*\*(\s*)\*\*/g, '$1').replace(/\s+/g, ' ').trim();
    const bullet = /<a:buChar|<a:buAutoNum/.test(p) && !/<a:buNone/.test(p);
    const level = +((/<a:pPr[^>]*\slvl="(\d+)"/.exec(p) || [])[1] || 0);
    out.push({ text, bullet, level, size: Math.max(...runs.map(r => r.size)), bold: runs.every(r => r.bold) });
  }
  return out;
}
function color(x) { const m = /<a:srgbClr val="([0-9A-Fa-f]{6})"/.exec(x); return m ? '#' + m[1].toUpperCase() : null; }
function lum(hex) { const [r, g, b] = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16) / 255); return 0.2126 * r + 0.7152 * g + 0.0722 * b; }
function hue(hex) {
  const [r, g, b] = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16) / 255);
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min;
  if (!d) return -1;
  let h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return h * 60;
}
function sat(hex) { const [r, g, b] = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16) / 255); const max = Math.max(r, g, b), min = Math.min(r, g, b); return max ? (max - min) / max : 0; }
// background color name for the .jmd: dark → accent/indigo, light → butter/lavender/wash/sky/white
function bgName(hex) {
  if (!hex) return 'white';
  const L = lum(hex), H = hue(hex), S = sat(hex);
  if (L < 0.35) return H >= 220 && H <= 280 && S > 0.5 ? 'accent' : 'indigo';
  if (L > 0.97 && S < 0.05) return 'white';
  if (L > 0.93 && S < 0.12) return 'white';
  if (H >= 170 && H <= 215) return S > 0.3 ? 'sky' : 'white';
  if (H >= 35 && H <= 65) return 'butter';
  if (H >= 230 && H <= 290) return L > 0.94 ? 'wash' : 'lavender';
  return L > 0.9 ? 'wash' : 'lavender';
}

/* ── one slide ────────────────────────────────────────────────────────── */
// the slide's master, through its layout: slide → layout → master
function masterOf(z, slideRels) {
  const lay = Object.values(slideRels).find(t => /slideLayouts\/slideLayout\d+\.xml$/.test(t));
  if (!lay) return null;
  const m = Object.values(rels(z, lay)).find(t => /slideMasters\/slideMaster\d+\.xml$/.test(t));
  return m && z.has(m) ? m : null;
}
function hasFullBleedPicture(xml) {
  return (xml.match(/<p:pic>[\s\S]*?<\/p:pic>/g) || []).some(pic => { const e = /<a:ext cx="(\d+)" cy="(\d+)"/.exec(pic); return e && +e[1] / EMU >= 900 && +e[2] / EMU >= 500; });
}

function readSlide(z, n, common, masterCache) {
  const path = `ppt/slides/slide${n}.xml`;
  const x = z.text(path); if (!x) return null;
  const r = rels(z, path);
  const master = masterOf(z, r);
  if (master && !(master in masterCache)) masterCache[master] = hasFullBleedPicture(z.text(master));
  const masterHasPicture = !!(master && masterCache[master]);
  // background: explicit <p:bg>, else the largest full-bleed filled rectangle
  const bgXml = (x.match(/<p:bg>[\s\S]*?<\/p:bg>/) || [''])[0];
  let bg = color(bgXml);
  const bgIsPicture = /<a:blip\b/.test(bgXml);
  const shapes = [], pics = [];
  for (const sp of x.match(/<p:sp>[\s\S]*?<\/p:sp>/g) || []) {
    const off = /<a:off x="(-?\d+)" y="(-?\d+)"/.exec(sp), ext = /<a:ext cx="(\d+)" cy="(\d+)"/.exec(sp);
    const box = off && ext ? { x: +off[1] / EMU, y: +off[2] / EMU, w: +ext[1] / EMU, h: +ext[2] / EMU } : { x: 0, y: 0, w: 0, h: 0 };
    const ph = (/<p:ph[^>]*type="([^"]+)"/.exec(sp) || [])[1] || (/<p:ph\b/.test(sp) ? 'body' : null);
    const paras = paragraphs(sp);
    if (!paras.length) {
      // a filled shape covering the slide → background
      const fill = color((sp.match(/<p:spPr[^>]*>[\s\S]*?<\/p:spPr>/) || [''])[0]);
      if (!bg && fill && box.w >= 900 && box.h >= 500) bg = fill;
      continue;
    }
    shapes.push({ box, ph, paras, size: Math.max(...paras.map(p => p.size)), text: paras.map(p => p.text).join(' ').replace(/\*\*/g, '') });
  }
  for (const pic of x.match(/<p:pic>[\s\S]*?<\/p:pic>/g) || []) {
    const id = (/r:embed="([^"]+)"/.exec(pic) || [])[1];
    const off = /<a:off x="(-?\d+)" y="(-?\d+)"/.exec(pic), ext = /<a:ext cx="(\d+)" cy="(\d+)"/.exec(pic);
    const file = id && r[id];
    if (!file || !z.has(file)) continue;
    const alt = cleanAlt(unesc((/<p:cNvPr[^>]*descr="([^"]*)"/.exec(pic) || /<p:cNvPr[^>]*name="([^"]*)"/.exec(pic) || [])[1] || ''));
    pics.push({ file, alt, box: off && ext ? { x: +off[1] / EMU, y: +off[2] / EMU, w: +ext[1] / EMU, h: +ext[2] / EMU } : { x: 0, y: 0, w: 0, h: 0 } });
  }
  // speaker notes
  const notesRel = Object.values(r).find(t => /notesSlides\/notesSlide\d+\.xml$/.test(t));
  let notes = '';
  if (notesRel && z.has(notesRel)) {
    const nx = z.text(notesRel);
    const body = (nx.match(/<p:sp>[\s\S]*?<\/p:sp>/g) || []).find(sp => /type="body"/.test(sp));
    notes = body ? paragraphs(body).map(p => p.text).join(' ').trim() : '';
  }
  // shared decorations: pictures that appear on most slides (logo, blob) are not content
  const bgPic = pics.find(p => p.box.w >= 900 && p.box.h >= 500);
  const content = pics.filter(p => p !== bgPic && !common.has(p.file) && p.box.w >= 12 && p.box.h >= 12);
  return { n, bg, bgPic: !!bgPic || bgIsPicture || (!bg && masterHasPicture), shapes, pics: content, notes, colors: [...x.matchAll(/<a:srgbClr val="([0-9A-Fa-f]{6})"/g)].map(m => '#' + m[1].toUpperCase()), fonts: [...x.matchAll(/typeface="([^"]+)"/g)].map(m => m[1]) };
}

/* ── the draft ────────────────────────────────────────────────────────── */
function draftSlide(s, mediaNames, isFirst, isLast, total) {
  const lines = [];
  const bg = s.bgPic && !s.bg ? 'accent' : bgName(s.bg); // a full-bleed picture: assume the brand's vivid background
  // title: the title placeholder, else the biggest font; eyebrow: a short small text above it
  const byTitle = s.shapes.filter(sh => /title/i.test(sh.ph || ''));
  const isNum = sh => sh.paras.length === 1 && /^[+~≈]?[\d\s.,]+\s*[%+KMk€$xX×]*\s*[+]?$/.test(sh.text.trim()) && sh.text.trim().length <= 8;
  const numCount = s.shapes.filter(isNum).length;
  const sorted = [...s.shapes].filter(sh => sh.text.replace(/\W/g, '').length >= 3 && !(numCount >= 2 && isNum(sh))).sort((a, b) => b.size - a.size);
  const title = (byTitle[0] && byTitle[0].text.replace(/\W/g, '').length >= 3 ? byTitle[0] : null) || sorted[0] || null;
  const rest = s.shapes.filter(sh => sh !== title).sort((a, b) => a.box.y - b.box.y || a.box.x - b.box.x);
  const eyebrow = title ? rest.find(sh => sh.box.y < title.box.y && sh.text.length <= 40 && sh.size <= (title.size || 99) * 0.7) : null;
  const meta = [`bg: ${bg}`];
  if (eyebrow) meta.push(`eyebrow: ${eyebrow.text}`);
  if (s.notes) meta.push(`notes: ${s.notes.replace(/\n/g, ' ')}`);
  lines.push('---', ...meta, '---');
  const cover = (isFirst || isLast) && s.shapes.length <= 3 && (bg === 'accent' || bg === 'indigo' || bg === 'sky');
  const onlyTitle = s.shapes.length === 1 && s.pics.length === 0;
  if (title && onlyTitle && !isFirst) {
    lines.push('::: section', title.text, ':::');
    return { lines, kind: 'section', bg, title: title.text };
  }
  if (title) lines.push((cover ? '# ' : '## ') + title.text.replace(/\s+/g, ' '));
  // body: every other text shape, in reading order; bullets kept, the first plain paragraph becomes the lead
  let body = rest.filter(sh => sh !== eyebrow);
  // numbers with a label each (a big "400K" and, right under it, "clients") → a metrics block
  const nums = body.filter(isNum), metrics = [];
  if (nums.length >= 2) {
    const labels = body.filter(sh => !isNum(sh) && sh.paras.length === 1 && sh.text.length <= 60);
    const pairs = [];
    for (const n of nums) {
      const under = labels.filter(l => !pairs.some(q => q.label === l) && l.box.y >= n.box.y && l.box.y - (n.box.y + n.box.h) < 60 && Math.abs(l.box.x - n.box.x) < Math.max(n.box.w, 120))
        .sort((a, b) => a.box.y - b.box.y)[0];
      if (under) pairs.push({ num: n, label: under });
    }
    if (pairs.length >= 2) {
      metrics.push('', '::: metrics', ...pairs.map(q => `- ${q.num.text.trim()} | ${q.label.text.trim()}`), ':::');
      body = body.filter(sh => !pairs.some(q => q.num === sh || q.label === sh));
    }
  }
  // a run of short one-paragraph boxes (a "list" made of separate text boxes) → bullets
  const shortBox = sh => sh.paras.length === 1 && !sh.paras[0].bullet && sh.text.length <= 60 && !/[.!?:]$/.test(sh.text.trim());
  const runs = []; let run = [];
  for (const sh of body) { if (shortBox(sh)) run.push(sh); else { if (run.length >= 3) runs.push(run); run = []; } }
  if (run.length >= 3) runs.push(run);
  const inRun = new Set(runs.flat());
  let leadDone = false, prevRun = false;
  for (const sh of body) {
    if (inRun.has(sh)) { if (!prevRun) lines.push(''); lines.push('- ' + sh.text.trim()); prevRun = true; continue; }
    prevRun = false;
    lines.push('');
    for (const p of sh.paras) {
      if (p.bullet || (sh.paras.length > 2 && p.text.length < 90 && !/[.!?]$/.test(p.text) && p.level === 0 && sh.paras.every(q => q.text.length < 120)))
        lines.push('- ' + p.text);
      else { lines.push(p.text); leadDone = true; }
    }
  }
  lines.push(...metrics); // after the text: title, lead, then the numbers
  // pictures: icons (tiny) and callouts (a picture sitting on a bigger one) are dropped; a row of wide small ones → logos;
  // the biggest on the right half → .right; the rest → figures
  const inside = (a, b) => a !== b && a.box.x >= b.box.x - 4 && a.box.y >= b.box.y - 4 && a.box.x + a.box.w <= b.box.x + b.box.w + 4 && a.box.y + a.box.h <= b.box.y + b.box.h + 4 && a.box.w * a.box.h < b.box.w * b.box.h * 0.6;
  const pics = s.pics.filter(p => mediaNames.has(p.file) && Math.max(p.box.w, p.box.h) >= 40 && !s.pics.some(q => inside(p, q))); // a 23×27 icon goes, an 82×33 logo stays; a media left out (exportMedia) is not named
  const logoLike = pics.filter(p => p.box.h <= 120 && p.box.w / p.box.h >= 1.4);
  const small = logoLike.length >= 3 && logoLike.length >= pics.length - 1 ? pics.filter(p => p.box.h <= 130) : pics.filter(p => p.box.h <= 60); // a wall takes the odd taller logo with it
  const big = pics.filter(p => !small.includes(p)).sort((a, b) => b.box.w * b.box.h - a.box.w * a.box.h);
  if (small.length >= 3) {
    lines.push('', '::: logos', ...small.map(p => `- ![${p.alt || 'logo'}](${mediaNames.get(p.file)})`), ':::');
  } else {
    for (const p of small) lines.push('', `![${p.alt}](${mediaNames.get(p.file)})`);
  }
  big.forEach((p, k) => {
    const mod = cover ? '{.cover}' : (k === 0 && p.box.x + p.box.w / 2 > 480 ? '{.right}' : (p.box.w > 700 ? '{.wide}' : ''));
    lines.push('', `![${p.alt}](${mediaNames.get(p.file)})${mod}`);
  });
  return { lines, kind: cover ? 'cover' : (big.length ? 'feature' : 'text'), bg, title: title ? title.text : '' };
}

/* ── media: copy, resize with Chrome when large ───────────────────────── */
export const PIXELS_MAX = 40_000_000; // a picture is decoded by Chrome only when its header says it fits (a 1 KB PNG can claim 30 000×30 000)
/** Width × height from the header of a PNG or a JPEG (what Chrome would allocate), null when unreadable. */
export function pixels(buf) {
  if (buf.length > 24 && buf[0] === 0x89 && buf[1] === 0x50 && buf.toString('latin1', 12, 16) === 'IHDR') return buf.readUInt32BE(16) * buf.readUInt32BE(20);
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    for (let p = 2; p + 9 < buf.length && buf[p] === 0xff;) {
      const m = buf[p + 1];
      if ((m >= 0xc0 && m <= 0xcf) && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) return buf.readUInt16BE(p + 5) * buf.readUInt16BE(p + 7); // SOFn: height, width
      if (m === 0xd8 || (m >= 0xd0 && m <= 0xd7) || m === 0x01) { p += 2; continue; }
      p += 2 + buf.readUInt16BE(p + 2);
    }
  }
  return null;
}
/* `media(base, ext, bytes)` → the reference the draft writes, or throws with the reason to leave that picture out: by default a
   file under <out>/media/; the hosted import gives a sink that puts the bytes in the user's drop box (mcp/tools.mjs), which refuses
   what a hand-dropped file would be refused for. `skipped` says what was left out and why; the draft never names it. */
async function exportMedia(z, files, outDir, { maxPx = 1400, maxBytes = 350_000, media = null } = {}) {
  const sink = media || ((base, ext, bytes) => { mkdirSync(join(outDir, 'media'), { recursive: true }); writeFileSync(join(outDir, `media/${base}.${ext}`), bytes); return `media/${base}.${ext}`; });
  const names = new Map(), skipped = [];
  let browser = null, page = null;
  try {
    for (const f of files) {
      let buf; try { buf = z.read(f); } catch (e) { skipped.push(`${basename(f)}: ${e.message.replace(/^.*?: /, '')}`); continue; }
      if (!buf) continue;
      let ext = f.split('.').pop().toLowerCase();
      const base = basename(f, '.' + ext).normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'image';
      let out = null;
      if (['png', 'jpg', 'jpeg', 'webp'].includes(ext) && buf.length > maxBytes) {
        const px = pixels(buf);
        if (px && px > PIXELS_MAX) { skipped.push(`${basename(f)}: ${Math.round(px / 1e6)} megapixels, too large to resize`); continue; }
        if (!browser) { browser = await Browser.launch(); page = await browser.page('about:blank'); }
        const mime = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
        const dataUrl = await page.eval(`(async () => {
          const img = new Image(); img.src = ${JSON.stringify('data:' + mime + ';base64,' + buf.toString('base64'))}; await img.decode();
          const s = Math.min(1, ${maxPx} / Math.max(img.naturalWidth, img.naturalHeight));
          const c = document.createElement('canvas'); c.width = Math.round(img.naturalWidth * s); c.height = Math.round(img.naturalHeight * s);
          const g = c.getContext('2d'); g.fillStyle = '#fff'; g.fillRect(0, 0, c.width, c.height); g.drawImage(img, 0, 0, c.width, c.height);
          return c.toDataURL('image/jpeg', 0.82);
        })()`);
        buf = Buffer.from(dataUrl.split(',')[1], 'base64'); ext = 'jpg';
      }
      try { out = sink(base, ext === 'jpeg' ? 'jpg' : ext, buf); } catch (e) { skipped.push(`${basename(f)}: ${e.message}`); continue; }
      if (out) names.set(f, out); else skipped.push(`${basename(f)}: not an image the deck can show`);
    }
  } finally { if (page) await page.close(); if (browser) browser.close(); }
  return { names, skipped };
}

/* ── brand draft from the colors and fonts actually used ──────────────── */
function brandDraft(slides, name) {
  const freq = {};
  slides.forEach(s => s.colors.forEach(c => { freq[c] = (freq[c] || 0) + 1; }));
  const cols = Object.entries(freq).sort((a, b) => b[1] - a[1]).map(([c]) => c);
  const pick = (f) => cols.find(f) || null;
  const primary = pick(c => lum(c) < 0.25 && sat(c) > 0.3);
  const ink = pick(c => lum(c) < 0.2) || primary;
  const accent = pick(c => lum(c) >= 0.25 && lum(c) < 0.6 && sat(c) > 0.45);
  const highlight = pick(c => hue(c) >= 35 && hue(c) <= 65 && lum(c) > 0.7);
  const secondary = pick(c => hue(c) >= 170 && hue(c) <= 215 && sat(c) > 0.4);
  const fonts = {};
  slides.forEach(s => s.fonts.forEach(f => { if (!/^\+/.test(f)) fonts[f] = (fonts[f] || 0) + 1; }));
  const font = Object.entries(fonts).sort((a, b) => b[1] - a[1]).map(([f]) => f)[0] || 'system-ui';
  return `# brand draft from ${name} — ${cols.length} colors seen; check every value, then save as themes/brands/<name>.yaml
name: ${name}
logo: jamespot
primary: "${primary || '#1B1A4E'}"
accent: "${accent || primary || '#8B7FE8'}"
highlight: "${highlight || '#FFD66B'}"
ink: "${ink || '#1B1A4E'}"
${secondary ? `secondary: "${secondary}"` : '# secondary: none seen'}
font-display: ${font}
font-body: ${font}
font-fallback: system-ui
# colors seen, most frequent first: ${cols.slice(0, 12).join(' ')}
`;
}

/* ── entry point ──────────────────────────────────────────────────────── */
export async function importPptx(pptxPath, outDir, opts = {}) {
  const z = readZip(readFileSync(pptxPath));
  const source = opts.source || basename(pptxPath); // the name the user knows the file by (hosted: as the box stored it)
  const slug = source.replace(/\.pptx$/i, '').replace(/[^\w-]+/g, '-').replace(/^-|-$/g, '').toLowerCase() || 'deck';
  mkdirSync(outDir, { recursive: true });
  const ids = z.names.map(n => /^ppt\/slides\/slide(\d+)\.xml$/.exec(n)).filter(Boolean).map(m => +m[1]).sort((a, b) => a - b);
  // pictures used on many slides are decoration
  const usage = {};
  for (const n of ids) for (const t of Object.values(rels(z, `ppt/slides/slide${n}.xml`))) if (/^ppt\/media\//.test(t)) usage[t] = (usage[t] || 0) + 1;
  const common = new Set(Object.entries(usage).filter(([, c]) => c >= 3 && ids.length >= 6).map(([f]) => f));
  // a full-bleed picture on a slide's master is the background of every slide (of that master) that does not paint its own
  const masterCache = {};
  const slides = ids.map(n => readSlide(z, n, common, masterCache)).filter(Boolean);
  const files = [...new Set(slides.flatMap(s => s.pics.map(p => p.file)))];
  const { names, skipped } = await exportMedia(z, files, outDir, opts);

  const title = (slides[0] && (slides[0].shapes.find(s => /title/i.test(s.ph || '')) || [...slides[0].shapes].sort((a, b) => b.size - a.size)[0]) || {}).text || slug;
  const core = z.text('docProps/core.xml') || '';
  const author = unesc(((/<dc:creator>([^<]*)<\/dc:creator>/.exec(core) || [])[1] || '').trim());
  const out = ['---', 'format: jmd/1', 'layout: slide', `title: ${title}`, 'theme: jamespot', `brand: ${opts.brand || 'jamespot'}`, `lang: ${opts.lang || 'fr'}`, `date: ${new Date().toISOString().slice(0, 10)}`, ...(author ? [`author: ${author}`] : []), `source: ${source}`, '---'];
  const report = [`# Import report — ${source}`, '', `${slides.length} slides · ${names.size} content images (${common.size} decorations skipped${skipped.length ? `, ${skipped.length} left out: ${skipped.join('; ')}` : ''}) · draft: ${slug}.jmd`, '', '| # | bg | kind | title | texts | images | notes |', '|---|---|---|---|---|---|---|'];
  slides.forEach((s, i) => {
    const d = draftSlide(s, names, i === 0, i === slides.length - 1, slides.length);
    out.push('', ...d.lines);
    report.push(`| ${i + 1} | ${d.bg} | ${d.kind} | ${d.title.slice(0, 50).replace(/\|/g, '/')} | ${s.shapes.length} | ${s.pics.length} | ${s.notes ? 'yes' : ''} |`);
  });
  report.push('', 'Every slide is a title + its text + its images. Restructure into blocks (cards, compare, metrics, timeline, pills, logos) by reading `spec/agents.md`, then run `jmd lint --dom` until clean.');
  const draft = out.join('\n') + '\n', reportText = report.join('\n') + '\n';
  writeFileSync(join(outDir, slug + '.jmd'), draft);
  writeFileSync(join(outDir, 'brand-draft.yaml'), brandDraft(slides, slug));
  writeFileSync(join(outDir, 'import-report.md'), reportText);
  return { slug, slides: slides.length, images: names.size, skipped: common.size, leftOut: skipped, media: [...names.values()], jmd: join(outDir, slug + '.jmd'), draft, report: reportText };
}
